version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
 
    ports:
      - "8000:8000"

  frontend:

    build:
      context: ./next-app
      dockerfile: Dockerfile
    container_name: frontend
 
    ports:
      - "3000:3000"
  
    environment:
      BACKEND_URL: "http://backend:8000"
  
    depends_on:
      - backend
