version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    environment:
      - MALLOC_ARENA_MAX=2
      - PYTHONMALLOC=malloc
      - WORKERS=2
      - PYTHONUNBUFFERED=1
      - MAX_WORKERS=2
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 4096

  frontend:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: "http://backend:8000"
      NODE_ENV: "production"
      NEXT_PUBLIC_MAX_BODY_SIZE: "10mb"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 1G
    depends_on:
      - backend
    restart: unless-stopped
